version: "3"
services:
  app:
    image: "node:10"
    user: "node"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: development
      PORT: 3000
      MAIL_SMTP_HOST: mailcatcher-server
      MAIL_SMTP_PORT: 1025
      REDIS_CONNECTION_STRING: redis://redis-server
      MONGO_CONNECTION_STRING: mongodb://mongo-server/dn-database
    ports:
      - 3000:3000
    command: npm run dev
  mongo:
    image: mongo
    restart: always
    container_name: mongo-server
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis
    restart: always
    container_name: redis-server
    expose:
      - 6379
  mailcatcher:
    image: yappabe/mailcatcher
    container_name: mailcatcher-server
    restart: always
    ports:
        - 1080:1080
        - 1025